import { Verse } from "@/types/domain";

export const LOCAL_VERSES: Verse[] = [
  {
    id: "rom323",
    reference: "Romans 3:23",
    translation: "NIV",
    parts: ["For all have ", " and fall ", " of the glory of God."],
    answers: ["SINNED", "SHORT"],
    decoys: ["FAILED", "AWAY", "FAR"],
    themeId: "doubt",
    themeLabel: "Doubt",
    devotional:
      "The first movement of grace is honesty. Scripture does not invite you to pretend that you are whole on your own; it invites you to come as someone who needs God.",
    applicationPrompt: "Where do you need to stop hiding weakness and ask God for mercy today?",
    difficulty: "beginner",
  },
  {
    id: "jn119",
    reference: "1 John 1:9",
    translation: "NIV",
    parts: [
      "If we ",
      " our sins, he is ",
      " and just and will ",
      " us our sins and ",
      " us from all unrighteousness.",
    ],
    answers: ["CONFESS", "FAITHFUL", "FORGIVE", "PURIFY"],
    decoys: ["HIDE", "CLEANSE", "FREE", "HOLY"],
    themeId: "temptation",
    themeLabel: "Temptation",
    devotional:
      "Confession is not a defeat. It is the place where God meets you with cleansing, truth, and a way back into the light.",
    applicationPrompt: "What temptation or compromise do you need to confess plainly before God today?",
    difficulty: "intermediate",
  },
  {
    id: "rom623",
    reference: "Romans 6:23",
    translation: "NIV",
    parts: [
      "For the wages of ",
      " is death, but the ",
      " of God is eternal ",
      " in Christ Jesus our Lord.",
    ],
    answers: ["SIN", "GIFT", "LIFE"],
    decoys: ["DEATH", "PEACE", "EVIL", "GRACE"],
    themeId: "hope",
    themeLabel: "Hope",
    devotional:
      "This verse names the seriousness of sin, but it does not end there. God meets what kills with a gift you could never earn: eternal life in Christ.",
    applicationPrompt: "How can you live today as someone who has received life as a gift, not earned it by striving?",
    difficulty: "beginner",
  },
  {
    id: "jn316",
    reference: "John 3:16",
    translation: "NIV",
    parts: [
      "For God so ",
      " the world that he ",
      " his one and only ",
      ", that whoever ",
      " in him shall not perish but have eternal life.",
    ],
    answers: ["LOVED", "GAVE", "SON", "BELIEVES"],
    decoys: ["SENT", "CHILD", "TRUSTS", "SAVED"],
    themeId: "hope",
    themeLabel: "Hope",
    devotional:
      "When your heart needs steady ground, begin with God's love. His gift in Christ is not thin encouragement; it is the deep assurance of salvation and life.",
    applicationPrompt: "What would it look like to live from God's love instead of from fear or scarcity today?",
    difficulty: "intermediate",
    isDailyFeatured: true,
  },
  {
    id: "php413",
    reference: "Philippians 4:13",
    translation: "NIV",
    parts: ["I can do all this through ", " who ", " me strength."],
    answers: ["CHRIST", "GIVES"],
    decoys: ["JESUS", "GOD", "LORD"],
    themeId: "fear",
    themeLabel: "Fear",
    devotional:
      "Strength in Scripture is not loud self-confidence. It is quiet dependence on Christ in the exact work, pressure, or obedience in front of you.",
    applicationPrompt: "Where do you need to lean on Christ's strength instead of your own resolve today?",
    difficulty: "beginner",
  },
  {
    id: "rom828",
    reference: "Romans 8:28",
    translation: "NIV",
    parts: [
      "And we know that in all things ",
      " works for the ",
      " of those who ",
      " him, who have been called according to his purpose.",
    ],
    answers: ["GOD", "GOOD", "LOVE"],
    decoys: ["JESUS", "GRACE", "BEST", "SEEK"],
    themeId: "hope",
    themeLabel: "Hope",
    devotional:
      "You may not see how every thread is being woven, but God is not absent from the unfinished places. Hope grows by remembering that His purpose is still at work.",
    applicationPrompt: "What unfinished situation do you need to entrust to God's good purpose today?",
    difficulty: "intermediate",
  },
  {
    id: "pro35",
    reference: "Proverbs 3:5-6",
    translation: "NIV",
    parts: [
      " ",
      " in the Lord with all your ",
      " and lean not on your own ",
      ". In all your ways ",
      " to him, and he will make your paths ",
      ".",
    ],
    answers: ["TRUST", "HEART", "UNDERSTANDING", "SUBMIT", "STRAIGHT"],
    decoys: ["BELIEVE", "SOUL", "WISDOM", "CLEAR"],
    themeId: "guidance",
    themeLabel: "Guidance",
    devotional:
      "Guidance often begins with surrender before it becomes clarity. The way forward is shaped by trust, not by controlling every outcome.",
    applicationPrompt: "What decision needs trust and submission before it needs another plan?",
    difficulty: "expert",
    isDailyFeatured: true,
  },
  {
    id: "jer2911",
    reference: "Jeremiah 29:11",
    translation: "NIV",
    parts: [
      "For I know the ",
      " I have for you, declares the Lord, plans to ",
      " you and not to harm you, plans to give you ",
      " and a future.",
    ],
    answers: ["PLANS", "PROSPER", "HOPE"],
    decoys: ["THOUGHTS", "BLESS", "PEACE"],
    themeId: "waiting",
    themeLabel: "Waiting",
    devotional:
      "Waiting can feel like silence, but God is not absent in it. His promises keep shaping a future even when you cannot yet see the whole path.",
    applicationPrompt: "What are you still waiting for, and how can you wait with faithful hope today?",
    difficulty: "beginner",
    isDailyFeatured: true,
  },
  {
    id: "matt1128",
    reference: "Matthew 11:28",
    translation: "NIV",
    parts: [
      "Come to me, all you who are ",
      " and ",
      ", and I will give you rest.",
    ],
    answers: ["WEARY", "BURDENED"],
    decoys: ["TIRED", "HEAVY", "BROKEN"],
    themeId: "anxiety",
    themeLabel: "Anxiety",
    devotional:
      "Jesus does not meet worn-down people with pressure. He meets them with an invitation to come close, bring the weight, and receive rest.",
    applicationPrompt: "What burden do you need to bring honestly to Jesus instead of carrying alone today?",
    difficulty: "beginner",
    isDailyFeatured: true,
  },
  {
    id: "ps4610",
    reference: "Psalm 46:10",
    translation: "NIV",
    parts: [
      "Be ",
      " and know that I am God. I will be ",
      " among the nations, I will be exalted in the earth.",
    ],
    answers: ["STILL", "EXALTED"],
    decoys: ["QUIET", "CALM", "PRAISED"],
    themeId: "fear",
    themeLabel: "Fear",
    devotional:
      "Stillness in Scripture is not passivity. It is a deliberate refusal to let panic speak louder than the presence and rule of God.",
    applicationPrompt: "Where do you need to become still enough to remember that God is above your fear today?",
    difficulty: "beginner",
    isDailyFeatured: true,
  },
];
